### ISSUE TITLE
In our specialities section, the background image is not covering complete background in mobile version of interior_designing_2 site

### ISSUE THREAD

**Issue by poojajps13** [poojajps13/Static-Websites#1]
**HTML**
`
<div id="frame3">
				<div class="specialities">
					<h1 class="heading" style="color: black; background-color: white;">
						OUR SPECIALITIES
					</h1>
				    <hr style="width: 50%; margin-top: -1em;">
				    <hr style="width: 25%; margin-top: 1em;">
				    <div class="divide">
						<div class="spec">	
				     		<img class="box" src="images/architecture.jpg" alt="architecture">			     
				     		<p>
				     			<span style="font-size: 1.5em; color: red;">
				     				Architecture
				     			</span>
				     			<br>
				     			<br>
				     			We all here not only decorate home from inside but also from outside.We always try to fulfil what the coustomer desires.You say and we will make in best possible way.You can select from many of our designs or we can create a new one according to the requirements.Not only homes but also other buildings like hospitals,complex are designed here.
				     		</p>
				     	</div>
					 	<br>
					 	<br>
				    	<div class="spec">	
				    		<img class="box" src="images/interior.jpg" alt="interior">
				    		<p>
				    			<span style="font-size: 1.5em; color: red;">
				    				Interior Designing
				    			</span>
				    			<br>
				    			<br>
				    			We understand your love for your belongings.It`s everyone`s dream to decore their home or place of work with their imagination and we ,do the work simple for you. When it comes to interior of a place than it is very much important that everything sets at the right place .
				    		</p>
				    	</div>
				    	<br>
						<br>
				    	<div class="spec">	
				    		<img class="box" src="images/3D.jpg" alt="3D">
				    		<p>
				    			<span style="font-size: 1.5em; color: red;">
				    				3D Designing
				    			</span>
				    			<br>
				    			<br>
				    			The outlook of anything can be made alive with 3D designing . 3D designing provides different dimensions to the map or design(interior as well as exterior).It makes easy for us as well as you to visiualize the final output from different directions and positions before the actual construction, so that you get fully satisfied and gets assue about your decision.
				    		</p>
				    	</div>
					</div>
					<br>
				</div>
			</div>
`
**CSS**
`
.specialities
				{
					background-image: url("images/background.jpg");
					background-repeat: no-repeat;
					background-attachment: fixed;
				}
`

_Check the complete code in  :   Interior designing repository/interior_designing_2 folder

SITE LINK  :    [http://interiordesigning.epizy.com/](url)

**Comment by pranjal0819** [comment]
use
**background-size: cover;**
in your css

**Comment by poojajps13** [comment]
Thankyou pranjal0819.
